### PR TITLE
Youtube clone

### PR DESCRIPTION
**Pull request by DennisOsido**
- Added Navigation Bar.
- Added Video Section.
- Added Sidebar.
- Made improvements to CSS and HTML.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this inside of 30 minutes for a full review and feedback

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job @Amr-Adel-Saad and @DennisOsido :handshake: 
Well done for getting this far. Please consider my comments below and treat them all as hard requirements :100: 

#### Descriptive Readme
Your Readme file will benefit from a work up. When you start to apply to jobs, potential employers will go through your Github account to see the way you work and may form an opinion of the kind of developer you are from what they see. As such, it is important to ensure that all your repositories look very neat and professional. That being said, please consider this [example](https://github.com/Oluwadamilareolusakin/show-junkie-frontend/blob/master/README.md) as what your Readme File should look like! :smile: 

#### Navigation
Please consider giving your navigation bar second looks, I have attached screenshots of the necessary requirements below as well as your current navigation bar and finally what it should look like
* Requirements
screenshot

* Where you are
screenshot

* What you should end up with
screenshot

#### Main Video Section
Please consider the following requirements for the main video section, as well as an example of exactly what it should look like at the end of this project

* Requirements
screenshot

* What you have
screenshot

* What you should have
screenshot
screenshot

#### Recommended videos
Please consider the following screenshots for the recommended videos section, and make the appropriate changes before your next review request

* Requirements
screenshot

* What you have
screenshot

* What you should have
screenshot

### Summary
Great job once again, you've done pretty well :ok_hand: Please conside incoporating the changes I've proposed into your project then request another review. I wish you all the best moving forward :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by Amr-Adel-Saad** [comment]
Hi Tolulope,
We have added some changes to the branch. We would like to know your thoughts about these changes.

**Comment by thsvr** [comment]
Project Under Review by Thaís Vieira

**Comment by thsvr** [comment]
### PROJECT APPROVED :1st_place_medal: :tada: 

Hi @Amr-Adel-Saad  and @DennisOsido :smile: 

Great job implementing the requirements, your page looks amazing. :tada: :tada: :tada: 

There are some **optional** requirements below, please consider them. **No need to submit for another review, your project is able to be submitted.** 

- you can use the `main` tag for the dominant content of the `body` of a document in the next projects;
- on the readme, you guys can add a screenshot of the page;
- on the readme, you guys can add more professional contacts, like linkedIn, email and GitHub links.

If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo]()

Happy coding and good luck on the next project :desktop_computer:

**Pull request merged**
